# name: Deploy master branch

# on:
#   push:
#     branches:
#     - main

# jobs:
#   call-reusable-workflow:
#     # with:
#     #   stage: prod
#     secrets:
#       AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
#       AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
#     # env:
#     # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#     # AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#     uses: ./.github/workflows/reusable-workflow.yml

name: Terraform Workspaces

on: workflow_dispatch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      # environmentdev: dev
      environment: prod


    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        PROD_AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
        PROD_AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Workflow
      working-directory: aws_s3_bucket
      run: |
        terraform init
        terraform workspace new ${{ env.environment }}
        terraform workspace select ${{ env.environment }} && terraform plan
        terraform workspace select ${{ env.environment }} && terraform apply -auto-approve
