name: Deploy master branch

on:
  push:
    branches:
    - main

jobs:
  call-reusable-workflow:
    with:
      stage: prod
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
    uses: ./.github/workflows/reusable-workflow.yml

